### ISSUE TITLE
Add necessary fields and additional models to Child model.

### ISSUE THREAD

**Issue by wilfredwee** [WilfredWee/ds-medical-care-web#13]
User Story: #4 

Needs to fit REDCap's data structure.

Hours logged: 1.5

**Comment by adrianclim** [comment]
Documentation/API/Anything for what is in the target REDCap database is required to complete work on this issue. 
(My research into this suggests REDCap uses a MySQL database. Getting the schema of this may be enough for me to finish this issue. Alternatively, the documentation or api to the target REDCap database may work as well.)

**Comment by adrianclim** [comment]
I'm trying to find a way to access the REDCAP schema/ documentation, is there any documentation at all? Didn't they have a booklet for this somewhere?

**Comment by wilfredwee** [comment]
https://neurodevnet.med.ualberta.ca/api/help/

Note that REDCap integration is de-prioritized pending better structuring of research data.

**Comment by wilfredwee** [comment]
This issue is closed as all necessary fields have been created. Please create a new issue if there's something else missed.
