### ISSUE TITLE
Need secret_settings python file

### ISSUE THREAD

**Issue by adrianclim** [WilfredWee/ds-medical-care-web#20]
If this file is just a config file, I suggest adding the file to the repository but to blank out the values and then to IM or email the values to the rest of us if they're needed.

**Comment by wilfredwee** [comment]
It'll be a bit awkward to handle different version of the file or add it to remote and then gitignore it later. I think keeping it out of source control is a better solution.

I will post it on IM.

**Comment by adrianclim** [comment]
Alright, This Issue can be closed then.
