### ISSUE TITLE
Bootstrap the Dev Ops environment.

### ISSUE THREAD

**Issue by wilfredwee** [WilfredWee/ds-medical-care-web#6]
User Story: #1 

Set up our build process. How do we collect static files? How do we separate between front and backend?

Logged: 3 hrs.

**Comment by adrianclim** [comment]
I'm not sure how node.js works but when I used Django in the past I stored static files in a directory and let Apache read files from there. 

Edit: Seems like I'm slow and you've done it already. How did you do it in node btw? I'm curious

**Comment by Slightly-Crazy** [comment]
Seems like I'm slow and you've done it already. How did you do it in node btw? I'm curious

**Comment by wilfredwee** [comment]
Node is just used as a runner for Webpack, we still use Django's static files to serve up the files.

**Comment by wilfredwee** [comment]
Dev Ops should be sufficiently bootstrapped. Will create additional tasks as needed as we go down the road. Closed.
